version: "3.9"

services:

  mongodb:
    container_name: brother_bank_db
    image: mongo:5.0.7
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data: